#!/usr/bin/env python3
# filepath: d:\Pyth\pythfarms\scripts\aero\lib\optimizer.py
"""
Aerodrome Vote Optimizer

This module optimizes vote allocation across Aerodrome pools using an equal-marginal utility algorithm
that maximizes combined returns from voter rewards (bribes + fees) and LP rewards.

REQUIRED INPUTS:
    - votes_dashboard.json: Pool voting data with rewards, weights, and LP positions
      Location: input_data/aero/votes_dashboard.json
      Generated by: fetch_votes.py
    
    - volatility_data.json (optional): Pool price volatility data for risk-adjusted optimization
      Location: volatility_data/aero/volatility_data.json
      Generated by: fetch_volatility.py
      Usage: Run optimizer with --with-volatility flag

OUTPUTS:
    - optimized_votes_human.json: Human-readable allocation with reward breakdowns
    - optimized_votes_bot.txt: Bot-formatted votes (pool_address weight) for on-chain submission
    Location: optimized_votes/aero/

CONFIGURATION:

Protocol Pool Minimums (PROTOCOL_POOL_MINIMUMS):
    Define minimum vote percentages for each protocol-owned pool:
    {
        "0x9e4cb8b916289864321661ce02cf66aa5ba63c94": Decimal("50"),  # vAMM-WETH/DEUS: 50%
        "0x982534133b2b71ab012404256be316344bb9f261": Decimal("10"),  # vAMM-cbBTC/DEUS: 10%
        "0xf185f82a1948d014bae23d30b06fa8da35110315": Decimal("10"),  # vAMM-USDC/DEUS: 10%
    }
    After minimums are allocated, remaining votes are optimized across all pools.

Blacklisted Pools (BLACKLISTED_POOLS):
    Pools to completely exclude from vote allocation:
    BLACKLISTED_POOLS = [
        "0xbd1f3d188de7ee07b1b323c0d26d6720cafb8780"  # Example: vAMM-fBOMB/wstETH
    ]

OPTIMIZATION FLOW:

1. Remove Foundation Votes:
   - Removes Ouranous Foundation's current votes from pool weights
   - Optimizes Foundation's votes first using equal-marginal algorithm
   
2. Remove Our Current Votes:
   - Removes our existing votes from pool weights to get clean baseline
   
3. Allocate Protocol Pool Minimums:
   - Guarantees minimum percentages to each protocol pool (e.g., 50% to WETH/DEUS)
   
4. Optimize Remaining Votes:
   - Runs equal-marginal optimization across ALL pools (protocol + regular)
   - Considers both voter rewards (bribes/fees) AND LP position rewards
   - Optional: Applies volatility penalty with --with-volatility flag
   
5. Generate Output:
   - Combines minimums + optimized allocations
   - Produces human-readable JSON and bot-ready text format

OPTIMIZATION ALGORITHM:

The equal-marginal algorithm allocates votes to equalize marginal utility across pools:
    
    Marginal Utility = Voter Marginal + LP Marginal
    
    Voter Marginal = (Reward * Weight) / (Weight + OurVotes)² × VolatilityPenalty
    LP Marginal = LPFraction × (WeeklyRewards / PoolWeight)
    
    With volatility penalty (--with-volatility):
    VolatilityPenalty = 1 - (2 × gamma × σ² × PoolShare × RewardValue)
    where σ = volatility percentage, gamma = penalty coefficient

USAGE:

Basic optimization:
    python scripts/aero/aero_manager.py optimize

With volatility adjustment:
    python scripts/aero/aero_manager.py optimize --with-volatility --gamma 1.0

NOTES:
    - Protocol pools receive minimum allocation + any additional optimal votes
    - Blacklisted pools are completely excluded from consideration
    - LP rewards are calculated from gauge reward rates when available
    - For protocol pools, we value other LPs' positions at 20% to incentivize growth
"""

import os
import json
import logging
from decimal import Decimal, getcontext, ROUND_HALF_UP

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Increase precision for allocation math
getcontext().prec = 50

# Constants
TOL = Decimal("1e-12")
MAX_ITERS = 100
TOP_N = 6  # For display
TOTAL_WEIGHT_TARGET = Decimal(100) * (Decimal(10) ** 18)  # sum weights to 100e18

# Individual minimum percentages for each protocol pool (percentage of total voting power)
PROTOCOL_POOL_MINIMUMS = {
    "0x9e4cb8b916289864321661ce02cf66aa5ba63c94": Decimal("50"),  # vAMM-WETH/DEUS: 50%
    "0x982534133b2b71ab012404256be316344bb9f261": Decimal("10"),  # vAMM-cbBTC/DEUS: 10%
    "0xf185f82a1948d014bae23d30b06fa8da35110315": Decimal("10"),  # vAMM-USDC/DEUS: 10%
}

# Calculate total minimum protocol percent from individual minimums
MINIMUM_PROTOCOL_PERCENT = sum(PROTOCOL_POOL_MINIMUMS.values())  # Should be 70%

# Blacklisted pools - we'll never allocate votes to these pools
# Add pool addresses (lowercase) to this list to prevent voting for them
BLACKLISTED_POOLS = [
    "0xbd1f3d188de7ee07b1b323c0d26d6720cafb8780" # Weth/fBomb
            ]

# Set to track protocol pool allocations to ensure they're included in final output
PROTOCOL_POOL_ALLOCATIONS = []

# Track which pools we've logged marginal calculations for
logged_pools = set()

# Helper function for human-readable vote formatting
def format_with_suffix(value):
    """Format a number with K/M suffix for human readability"""
    if value >= 1_000_000:
        return f"{value/1_000_000:.1f}M"
    elif value >= 1_000:
        return f"{value/1_000:.1f}K"
    else:
        return f"{value:.1f}"

# Default paths
DEFAULT_DASHBOARD_PATH = "input_data/aero/votes_dashboard.json"
# We don't need LP dashboard anymore as it's integrated into votes dashboard
# DEFAULT_LP_DASHBOARD_PATH = "lp_dashboard/aero/lp_dashboard.json" 
HUMAN_OUT_PATH = "optimized_votes/aero/optimized_votes_human.json"
BOT_OUT_PATH = "optimized_votes/aero/optimized_votes_bot.txt"
CALLDATA_OUT_PATH = "optimized_votes/aero/optimized_votes_calldata.json"

def load_json(path):
    """Load a JSON file or exit if missing"""
    if not os.path.exists(path):
        logger.error(f"❌ {path} not found.")
        return None
    with open(path) as f:
        return json.load(f)

def save_json(data, path):
    """Save data to a JSON file"""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        json.dump(data, f, indent=2)
    logger.info(f"✅ Saved data to {path}")

def save_text(text, path):
    """Save text to a file"""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write(text)
    logger.info(f"✅ Saved text to {path}")

def equal_marginal_combined(pool_data, P, S_total, total_emissions=None, gamma=1, pools_data=None):
    """
    Enhanced equal-marginal solver: maximizes total value (voting rewards + LP rewards)
    with volatility adjustment
    
    Args:
        pool_data: List of tuples (pool_addr, reward, weight, lp_fraction, weekly_rewards_usd, volatility)
        P: Total voting power to allocate
        external_votes: Total system votes (sum of all pool weights + P)
        total_emissions: (deprecated, kept for compatibility)
        gamma: Volatility penalty coefficient (default 1)
        pools_data: Original pools data with on_chain_weight information
    
    Returns:
        List of tuples (pool_addr, allocation)
    """
    # Convert gamma to Decimal
    gamma = Decimal(str(gamma))
    
    # Filter for potentially active pools (either has rewards or has our LP) and not blacklisted
    active = [(p, R, W, lp, wk_r, vol) for (p, R, W, lp, wk_r, vol) in pool_data 
              if (R > 0 or lp > 0) and W >= 0 and p not in BLACKLISTED_POOLS]
    if not active:
        return [(p, Decimal(0)) for (p, _, _, _, _, _) in pool_data]

    # Small floor for division safety
    EPSILON = Decimal("1e-12")
    
    # Create a mapping of on-chain weights for easier lookup
    ocw_map = {}
    if pools_data:
        for p in pools_data:
            ocw_map[p["pool"].lower()] = Decimal(str(p.get("on_chain_weight", p.get("weight", 0))))
    
    def voter_marginal(R, W, our_votes, volatility=Decimal(0), S_tot=None):
        # R are the value of rewards (bribes and fees), and delta are our votes; W the external votes
        if R <= 0:
            return Decimal(0)
        EPSILON = Decimal("1e-12")
        external_votes = max(W, EPSILON) # making external vote for a pool non zero

        # base marginal -- derivative of R * P_share
        base = R * external_votes / (external_votes + our_votes)**2 # marginal

        # exposure-aware penalty
        P_share = ((external_votes + our_votes) / S_tot) if S_tot and S_tot > 0 else Decimal(0)
        sigma = Decimal(volatility) / Decimal(100)  # turn % into decimal; volatility of the token reward

        risk_mult = Decimal(1) - (2 * gamma * (sigma**2) * P_share * R) # second part is the penalty for the volatility... divided by "base"
        # we already have one time R in base, so in risk_multi it's only R not R**2
        # need to multiply by the value of the (risky) reward token
        # We need to modify R in the risk multiplier, and only use the volatile rewards
        # ( bcs the USDC/Eth/BTC rewards are not penalised
        if risk_mult < 0: risk_mult = Decimal(0)
        if risk_mult > 1: risk_mult = Decimal(1)

        return base * risk_mult

    
    def lp_marginal(lp_frac, weekly_rewards, W, delta, S_tot, on_chain_weight=None):
        """LP-side marginal utility per vote with adjusted reward rate"""
        '''The Marginal wrt delta (our votes) is almost 1/P -- just one more vote on that pool'''
        
        if lp_frac <= 0 or weekly_rewards <= 0:
            return Decimal(0)
        
        # Ensure we don't have division by zero
        if on_chain_weight is None or on_chain_weight <= EPSILON:
            # Fall back to the old behavior if on_chain_weight is not provided
            return lp_frac * weekly_rewards / P
        
        # Calculate the reward increase per vote based on how adding votes changes the reward rate
        # When we add votes, the reward scales proportionally to the new total vs original total
        # Example:
        # - Current: 100 votes, 10 AERO rewards
        # - Adding 20 votes (delta=20) means new total = 120 votes
        # - New reward = (120/100) *     10 = 12 AERO
        # - Additional reward from our vote = 12 - 10 = 2 AERO for 20 votes
        # - So each vote contributes 2/20 = 0.1 AERO of additional reward
        
        # For derivatives, we need: d/dδ[weekly_rewards * (W + δ) / on_chain_weight]
        # This equals: weekly_rewards / on_chain_weight
        
        # This is the marginal increase in rewards from adding one more vote
        reward_per_vote = weekly_rewards / on_chain_weight
        
        # Return the marginal utility per vote
        return lp_frac * reward_per_vote    
    

    # Store the top marginal utility values to compare
    top_marginals = []
    def record_top_marginal(addr, R, W, lp_frac, weekly_rewards, vm, lm, total):
        """Record top marginal utility for comparison"""
        nonlocal top_marginals
        
        # Check if this pool is already in the list to avoid duplicates
        existing_pool_index = next((i for i, p in enumerate(top_marginals) if p[0] == addr), None)
        
        if existing_pool_index is not None:
            # Update existing entry if it's already in the list
            top_marginals[existing_pool_index] = (addr, R, W, lp_frac, weekly_rewards, vm, lm, total)
        else:
            # Add new entry if pool not already in the list
            top_marginals.append((addr, R, W, lp_frac, weekly_rewards, vm, lm, total))
            
        top_marginals.sort(key=lambda x: x[7], reverse=True)  # Sort by total marginal
        if len(top_marginals) > 10:
            top_marginals = top_marginals[:10]  # Keep only top 10
    
    def total_marginal(R, W, lp_frac, weekly_rewards, delta, S_tot, addr="unknown", volatility=Decimal(0)):
        """Combined marginal utility per vote"""
        global logged_pools
        
        vm = voter_marginal(R, W, delta, volatility, S_tot)
        
        # Get on-chain weight from our mapping or fall back to W
        on_chain_weight = ocw_map.get(addr, W) if addr in ocw_map else W
        lm = lp_marginal(lp_frac, weekly_rewards, W, delta, S_tot, on_chain_weight)
        total = vm + lm
        
        # Record for comparison only once at the initial calculation
        if delta == 0:
            record_top_marginal(addr, R, W, lp_frac, weekly_rewards, vm, lm, total)
        
        # Add debug logging for pools where we have LP positions or significant volatility, but only once per pool
        if (lp_frac > 0 or volatility > 5) and delta == 0 and addr not in logged_pools:
            penalty = ""
            if gamma > 0 and volatility > 0:
                volatility_penalty = max(Decimal(0), Decimal(1) - (volatility / Decimal(100) * gamma))
                penalty = f", penalty={volatility_penalty:.4f}"
                
            # logger.info(f"Marginal calc: R=${R:.2f}, W={W:.2f}, lp_frac={lp_frac:.6f}, volatility={volatility:.2f}%{penalty}, delta={delta:.2f}")
            # logger.info(f"  → VM={vm:.6f}, LM={lm:.6f}, Total={vm+lm:.6f}")
            logged_pools.add(addr)
            
        return total
    
    def find_delta_for_pool(R, W, lp_frac, weekly_rewards, lam, S_tot, addr="unknown", volatility=Decimal(0)):
        """Find delta for a single pool using bisection"""
        if R <= 0 and lp_frac <= 0:
            return Decimal(0)
        
        # For pure voter reward pools with no LP position, we can use the closed form
        if lp_frac <= 0 and gamma == 0:
            # Only use closed form if no volatility adjustment
            d = ((R * W) / lam).sqrt() - W
            return d if d > 0 else Decimal(0)
        
        # For pools with LP positions or with volatility adjustment, we need to solve with bisection
        # Start with a reasonable range: 0 to P (all votes)
        lo, hi = Decimal(0), P
        
        # Edge case: check if we should allocate no votes
        if total_marginal(R, W, lp_frac, weekly_rewards, lo, S_tot, addr, volatility) <= lam:
            return Decimal(0)
        
        # Bisection search for delta where total_marginal = lambda
        for _ in range(40):  # Usually converges in ~30 iterations for good precision
            mid = (lo + hi) / 2
            marg = total_marginal(R, W, lp_frac, weekly_rewards, mid, S_tot, addr, volatility)
            
            if abs(marg - lam) < TOL:
                return mid
            
            if marg > lam:
                lo = mid
            else:
                hi = mid
        
        return lo  # Return our best approximation
    
    def sum_delta(lam):
        """Sum of allocations across all pools for a given lambda"""
        s = Decimal(0)
        for addr, R, W, lp_frac, weekly_rewards, volatility in active:
            d = find_delta_for_pool(R, W, lp_frac, weekly_rewards, lam, S_total, addr, volatility)
            if d > 0:
                s += d
        return s
    
    # bracket λ so sum_delta(hi) < P
    lo, hi = Decimal("1e-30"), Decimal("1")
    for _ in range(200):
        if sum_delta(hi) < P:
            break
        hi *= 2
    else:
        raise RuntimeError("Could not bracket lambda for equal-marginal")
    
    # binary search for λ
    for _ in range(MAX_ITERS):
        mid = (lo + hi) / 2
        s = sum_delta(mid)
        if abs(s - P) < TOL:
            lo = mid
            break
        if s > P:
            lo = mid
        else:
            hi = mid
    lam = lo
    
    # compute Δ_i for each pool
    out = []
    for p, R, W, lp_frac, weekly_rewards, volatility in pool_data:
        if (R <= 0 and lp_frac <= 0) or W < 0:
            out.append((p, Decimal(0)))
        else:
            d = find_delta_for_pool(R, W, lp_frac, weekly_rewards, lam, S_total, p, volatility)
            out.append((p, d if d > 0 else Decimal(0)))
    
    # Display top marginal utilities for comparison
    logger.info("\nTop 10 pools by initial marginal utility:")
    if gamma > 0:
        logger.info("-----------------------------------------------------------------------------------------------")
        logger.info("Pool                R        Weight    LP Frac   LP Rewards   Vol %     Voter MU    LP MU    Total MU")
        logger.info("-----------------------------------------------------------------------------------------------")
    else:
        logger.info("----------------------------------------------------------------")
        logger.info("Pool                R        Weight    LP Frac   LP Rewards   Voter MU    LP MU    Total MU")
        logger.info("----------------------------------------------------------------")
    
    for addr, R, W, lp_frac, weekly_rewards, vm, lm, total in top_marginals:
        pool_name = addr[:10]  # We'll improve this in the full output
        volatility = next((v for p, _, _, _, _, v in active if p == addr), Decimal(0))
        
        if gamma > 0:
            logger.info(f"{pool_name:<10} ${R:<9.2f} {W:<10.2f} {lp_frac:<9.6f} ${weekly_rewards:<10.2f} {volatility:<8.2f} {vm:<10.6f} {lm:<8.6f} {total:<10.6f}")
        else:
            logger.info(f"{pool_name:<10} ${R:<9.2f} {W:<10.2f} {lp_frac:<9.6f} ${weekly_rewards:<10.2f} {vm:<10.6f} {lm:<8.6f} {total:<10.6f}")
    
    return out

def run_optimization(dashboard, volatility_data=None, gamma=0, minimum_protocol_percent=MINIMUM_PROTOCOL_PERCENT):
    """
    Run the optimization algorithm
    
    Args:
        dashboard: The votes dashboard with pool data (now includes LP data)
        volatility_data: Volatility data for pools
        gamma: Volatility penalty coefficient (0 = no penalty, default)
        minimum_protocol_percent: Minimum percentage to allocate to protocol pools
    
    Returns:
        Tuple of (result_dict, bot_output_string)
    """
    global logged_pools
    logged_pools.clear()  # Reset logged pools for new optimization run
    
    # Log if any pools are blacklisted
    if BLACKLISTED_POOLS:
        logger.info(f"⚠️ {len(BLACKLISTED_POOLS)} pools are blacklisted and will be excluded from vote allocation")
        for addr in BLACKLISTED_POOLS:
            # Find the pool data if available
            pool = next((p for p in dashboard.get("pools", []) if p.get("pool", "").lower() == addr), None)
            symbol = pool.get("symbol", addr) if pool else addr
            logger.info(f"   - Blacklisted: {symbol} ({addr[:10]}...)")
    
    # Convert gamma to Decimal
    gamma = Decimal(str(gamma))
    
    # Check if Ouranous Foundation relay exists
    ouranous_relay = None
    if "relays" in dashboard:
        for relay in dashboard["relays"]:
            if relay.get("name") == "Ouranous Foundation":
                ouranous_relay = relay
                logger.info(f"Found Ouranous Foundation relay with {relay.get('voting_amount', '?')} voting power")
                break
            
    # Load volatility data if not provided
    if volatility_data is None and gamma > 0:
        volatility_path = "volatility_data/aero/volatility_data.json"
        try:
            with open(volatility_path, 'r') as f:
                volatility_data = json.load(f)
            logger.info(f"Loaded volatility data with {len(volatility_data.get('pools', {}))} pools")
        except Exception as e:
            logger.warning(f"Could not load volatility data: {e}")
            volatility_data = {"pools": {}}
            
    # If gamma is enabled, log the volatility penalty setting
    if gamma > 0:
        logger.info(f"Using volatility penalty with gamma={gamma}")
    else:
        logger.info("Volatility penalty is disabled (gamma=0)")
    
    # First, get the pools so we can check for address matches
    pools = dashboard["pools"]
    
    # Create a mapping of volatility data by pool address
    volatility_map = {}
    if gamma > 0 and volatility_data and "pools" in volatility_data:
        pool_count = 0
        volatility_count = 0
        
        for addr, pool_data in volatility_data.get("pools", {}).items():
            pool_count += 1
            if "price_range" in pool_data and "volatility_percentage" in pool_data["price_range"]:
                vol_pct = pool_data["price_range"]["volatility_percentage"]
                # Make sure to normalize addresses to lowercase
                normalized_addr = addr.lower()
                volatility_map[normalized_addr] = Decimal(str(vol_pct))
                volatility_count += 1
                
                # Log pools with high volatility
                # if vol_pct > 10:
                    # symbol = pool_data.get("symbol", addr[:10])
                    # logger.info(f"High volatility detected: {symbol} - {vol_pct:.2f}%")
        
        logger.info(f"Loaded volatility data for {volatility_count} out of {pool_count} pools")
        
        # Debug to check if addresses match between volatility data and votes data
        if volatility_count > 0:
            votes_addresses = set(p["pool"].lower() for p in pools)
            volatility_addresses = set(volatility_map.keys())
            common_addresses = votes_addresses.intersection(volatility_addresses)
            logger.info(f"Found {len(common_addresses)} pools with both votes and volatility data")
            
            # Print sample addresses from each set for debugging
            if len(common_addresses) == 0:
                logger.warning("⚠️ No address matches between volatility data and votes dashboard!")
                logger.info(f"Sample vote addresses: {list(votes_addresses)[:3]}")
                logger.info(f"Sample volatility addresses: {list(volatility_addresses)[:3]}")
        
    # First remove our votes and Ouranous Foundation's votes from the pools
    # optim Ouranous Foundation's votes first, then our votes
    
    for p in pools:
        pool_addr = p["pool"].lower()
        our_votes = Decimal(str(p.get("our_votes", 0)))
        current_weight = Decimal(str(p.get("on_chain_weight", p.get("weight", 0))))
        
        # Remove Ouranous Foundation's current votes if they exist
        ouranous_votes = Decimal(0)
        if ouranous_relay:
            for vote in ouranous_relay.get("votes", []):
                if vote.get("pool", "").lower() == pool_addr:
                    ouranous_votes = Decimal(str(vote.get("weight", 0)))
                    break
        
        # Subtract just*** Ouranous Foundation's votes from the pool's weight before we optim for them
        adjusted_weight = max(current_weight - ouranous_votes, Decimal(0))
        
        # if our_votes > 0 or ouranous_votes > 0:
            # logger.info(f"Adjusting pool {p.get('symbol', '')} ({p['pool'][:10]}...):")
            # logger.info(f"  Original weight: {current_weight}")
            # if ouranous_votes > 0:
                 # logger.info(f"  Removing Ouranous votes: -{ouranous_votes}")
            # if our_votes > 0:
                # logger.info(f"  Removing our votes: -{our_votes}")
            # logger.info(f"  Adjusted weight: {adjusted_weight}")
            
        # Add adjusted weight directly to the pool data
        p["adjusted_weight"] = adjusted_weight
    
    # Now continue with the original logic
    P_our = Decimal(str(dashboard.get("our_voting_power", 0)))
    
    logger.info(f"Our total voting power: {P_our}")
    
    # Create a mapping of LP data by pool address from the integrated LP data in votes dashboard
    lp_data = {}
    logger.info("Extracting LP data from votes dashboard...")
    
    for pool in dashboard["pools"]:
        addr = pool.get("pool", "").lower()
        if not addr:
            continue
            
        # Check if this pool has our LP or is a protocol pool
        has_our_lp = pool.get("has_our_lp", False)
        is_protocol_pool = pool.get("is_protocol_pool", False)
        
        if has_our_lp or is_protocol_pool:
            # Get our LP data
            our_lp_data = pool.get("our_lp_data", {})
            tvl_usd = Decimal(str(our_lp_data.get("total_pool_tvl", 0)))
            our_lp_value = Decimal(str(our_lp_data.get("total_value_usd", 0)))
            
            # Calculate our LP fraction
            lp_fraction = Decimal(0)
            
            if tvl_usd > 0:
                # For protocol pools, we care about both our LP rewards and other LPs' rewards
                if is_protocol_pool:
                    # First, calculate our direct ownership percentage
                    if has_our_lp:
                        our_ownership = our_lp_value / tvl_usd
                    else:
                        our_ownership = Decimal(0)
                    
                    # Value other LPs' portion at 20% (0.2x)
                    other_lp_value_weight = Decimal("0.2")
                    other_lp_portion = Decimal(1) - our_ownership
                    
                    # Effective LP fraction = our_portion + (other_portion * 0.2)
                    lp_fraction = our_ownership + (other_lp_portion * other_lp_value_weight)
                    
                    logger.info(f"Protocol pool {pool.get('symbol', '')}: Our ownership={float(our_ownership*100):.2f}%, " +
                                f"Valuing other LP at 20% -> Effective LP fraction={float(lp_fraction*100):.2f}%")
                
                # For non-protocol pools with our LP, just use our ownership percentage
                elif has_our_lp:
                    lp_fraction = our_lp_value / tvl_usd
                    # Or use the pre-calculated ownership percentage
                    ownership_pct = Decimal(str(our_lp_data.get("ownership_percentage", 0)))
                    if ownership_pct > 0:
                        lp_fraction = ownership_pct / 100
            
            # Get reward rate data if available
            reward_rate_raw = None
            reward_usd_per_day = None
            reward_usd_per_week = None
            
            if our_lp_data:
                # Try to get reward rate from our LP data
                reward_rate_raw_str = our_lp_data.get("reward_rate_raw")
                if reward_rate_raw_str:
                    try:
                        reward_rate_raw = Decimal(str(reward_rate_raw_str))
                        # Get the pre-calculated USD values if available
                        reward_usd_per_day = Decimal(str(our_lp_data.get("reward_usd_per_day", 0)))
                        reward_usd_per_week = reward_usd_per_day * 7 if reward_usd_per_day else None
                    except (ValueError, TypeError):
                        reward_rate_raw = None
            
            # If we have reward rate data, use it for weekly rewards
            if reward_usd_per_week is not None and reward_usd_per_week > 0:
                weekly_rewards_usd = reward_usd_per_week
                logger.info(f"Using reward rate for {pool.get('symbol', '')}: ${float(weekly_rewards_usd):.2f}/week")
            else:
                # Fallback to calculating weekly rewards based on daily fees
                weekly_rewards_usd = Decimal(str(pool.get("fees_usd", 0))) * 7  # Weekly = 7 * daily fees
                logger.info(f"Using fees for {pool.get('symbol', '')}: ${float(weekly_rewards_usd):.2f}/week (reward rate not available)")
            
            lp_data[addr] = {
                "lp_fraction": lp_fraction,
                "weekly_rewards_usd": weekly_rewards_usd,
                "reward_rate_raw": reward_rate_raw,
                "reward_usd_per_day": reward_usd_per_day
            }
    
    # if Foundation exists, optimize their votes first
    ouranous_allocations = {}
    if ouranous_relay:
        # Get Ouranous Foundation's voting power
        P_ouranous = Decimal(str(ouranous_relay.get("voting_amount_raw", 0)))
        
        if P_ouranous > 0:
            logger.info(f"Optimizing Ouranous Foundation votes first with {P_ouranous} voting power...")
            
            # Calculate initial system votes without our votes or Ouranous votes
            # Also exclude blacklisted pools from this calculation
            S_initial = sum(Decimal(str(p.get("adjusted_weight", 0))) 
                           for p in pools if p["pool"].lower() not in BLACKLISTED_POOLS)
            logger.info(f"Initial system votes (without our votes or Ouranous votes, excluding blacklisted pools): {S_initial}")
            
            # Build combined data for each pool for Ouranous optimization (use the same logic as for our optimization)
            ouranous_pool_data = []
            ouranous_excluded_pools = []
            
            for p in pools:
                addr = p["pool"].lower()
                
                # Skip blacklisted pools for Ouranous optimization as well
                if addr in BLACKLISTED_POOLS:
                    ouranous_excluded_pools.append((addr, p.get("symbol", addr)))
                    continue
                    
                R = Decimal(str(p.get("total_usd", 0)))
                W = Decimal(str(p.get("adjusted_weight", 0)))
                
                # Get LP data (Ouranous doesn't have LP positions, but keep structure the same)
                lp_fraction = Decimal(0)
                weekly_rewards_usd = Decimal(0)
                
                # Ouranous Foundation always optimizes without volatility - don't use volatility data
                volatility = Decimal(0)
                
                ouranous_pool_data.append((addr, R, W, lp_fraction, weekly_rewards_usd, volatility))
                
            # Log excluded pools for Ouranous optimization
            if ouranous_excluded_pools:
                logger.info(f"Excluded {len(ouranous_excluded_pools)} blacklisted pools from Ouranous Foundation optimization:")
            
            # Optimize Ouranous Foundation's votes WITHOUT volatility penalties (always use gamma=0)
            logger.info(f"Allocating {P_ouranous} votes for Ouranous Foundation (without volatility) using equal-marginal algorithm...")
            ouranous_result = equal_marginal_combined(ouranous_pool_data, P_ouranous, S_initial + P_ouranous, None, 0, pools)
            
            # Convert result to a dictionary for easier lookup
            for addr, alloc in ouranous_result:
                if alloc > 0:
                    ouranous_allocations[addr] = alloc
                    
                    # Find the pool data to log the allocation
                    pool = next((p for p in pools if p["pool"].lower() == addr), None)
                    # if pool:
                        # logger.info(f"Ouranous Foundation allocated {alloc} votes to {pool.get('symbol', addr[:10])}")
                        
                    # Add the allocation to the pool's adjusted weight for our optimization
                    for p in pools:
                        if p["pool"].lower() == addr:
                            p["adjusted_weight"] += alloc
                            break
            
            logger.info(f"Ouranous Foundation optimized votes applied to {len(ouranous_allocations)} pools")
    
    logger.info("Removing our votes from pool weights for our optimization...")
    for p in pools:
        our_votes = Decimal(str(p.get("our_votes", 0)))
        if our_votes > 0:
            p["adjusted_weight"] = max(p["adjusted_weight"] - our_votes, Decimal(0))
            logger.info(f"Removed {our_votes} of our votes from {p.get('symbol', '')} (new adjusted_weight: {p['adjusted_weight']})")

    # Calculate total system votes (now including optimized Ouranous votes but not our votes)
    # Exclude blacklisted pools from the total system votes calculation
    S_total = sum(Decimal(str(p.get("adjusted_weight", p.get("on_chain_weight", p.get("weight", 0)))))
               for p in pools if p["pool"].lower() not in BLACKLISTED_POOLS)
    S_total += P_our  # Add our votes to get total system votes
    logger.info(f"Total system votes (with optimized Ouranous votes, excluding blacklisted pools): {S_total}")
    
    # Build combined data for each pool (voter rewards + LP data + volatility)
    combined_data = []
    
    # Track how many pools were excluded due to blacklisting
    excluded_pools = []
    
    for p in pools:
        addr = p["pool"].lower()
        
        # Skip blacklisted pools entirely - as if they don't exist for our optimization
        if addr in BLACKLISTED_POOLS:
            excluded_pools.append((addr, p.get("symbol", addr)))
            continue
            
        R = Decimal(str(p.get("total_usd", 0)))
        # Use adjusted_weight which has our votes removed
        W = Decimal(str(p.get("adjusted_weight", p.get("on_chain_weight", p.get("weight", 0)))))
        
        # Get LP data if available
        lp_fraction = Decimal(0)
        weekly_rewards_usd = Decimal(0)
        if addr in lp_data:
            lp_fraction = lp_data[addr]["lp_fraction"]
            weekly_rewards_usd = lp_data[addr]["weekly_rewards_usd"]
        
        # Get volatility data if available
        volatility = Decimal(0)
        if gamma > 0 and addr in volatility_map:
            volatility = volatility_map[addr]
            
            # If we have volatility data and are applying a penalty, log for significant pools
            if volatility > 0 and (R > 50 or lp_fraction > 0):
                sym = p.get("symbol", addr[:10])
                # logger.info(f"Pool {sym}: Applying volatility penalty of {volatility:.2f}% with gamma={gamma}")
        
        combined_data.append((addr, R, W, lp_fraction, weekly_rewards_usd, volatility))
    
    # Log how many pools were excluded due to blacklisting
    if excluded_pools:
        logger.info(f"Excluded {len(excluded_pools)} blacklisted pools from optimization process:")
        for addr, symbol in excluded_pools:
            logger.info(f"   - Excluded: {symbol} ({addr[:10]}...)")
    
    # Check if we have voting power to allocate
    if P_our <= 0:
        logger.error("❌ No voting power available to allocate. Exiting optimization.")
        return {"total_expected_usd": 0, "allocations": []}, ""
    
    # We no longer use total_emissions_usd since we get direct reward rates from gauges
    
    # Clear any previous protocol pool allocations
    global PROTOCOL_POOL_ALLOCATIONS
    PROTOCOL_POOL_ALLOCATIONS = []
    
    # Separate protocol pools for special handling
    protocol_pools_list = [addr.lower() for addr in dashboard.get("protocol_pools", [])]
    if protocol_pools_list:
        logger.info(f"Found {len(protocol_pools_list)} protocol pools: {', '.join(p[:10] + '...' for p in protocol_pools_list)}")
        
        # Check for protocol pools that might be blacklisted
        blacklisted_protocol_pools = [p for p in protocol_pools_list if p.lower() in BLACKLISTED_POOLS]
        if blacklisted_protocol_pools:
            logger.warning(f"WARNING: {len(blacklisted_protocol_pools)} protocol pools are blacklisted: {', '.join(p[:10] + '...' for p in blacklisted_protocol_pools)}")
            # Remove blacklisted protocol pools from the list
            protocol_pools_list = [p for p in protocol_pools_list if p.lower() not in BLACKLISTED_POOLS]
            logger.info(f"Using {len(protocol_pools_list)} non-blacklisted protocol pools")
    else:
        logger.warning("No protocol pools found in dashboard")
    
    # Get protocol pool symbols for better logging
    protocol_pool_symbols = {}
    for p in pools:
        addr = p["pool"].lower()
        if addr in protocol_pools_list:
            protocol_pool_symbols[addr] = p.get("symbol", addr[:10])
    
    # Split our data into protocol pools and regular pools
    protocol_pool_data = []
    regular_pool_data = []
    
    for data_entry in combined_data:
        addr = data_entry[0].lower()
        if addr in protocol_pools_list:
            protocol_pool_data.append(data_entry)
        else:
            regular_pool_data.append(data_entry)
    
    # Calculate individual minimum allocations for each protocol pool
    protocol_pool_minimum_votes = {}
    total_minimum_votes = Decimal(0)
    
    logger.info("Protocol pool minimum allocations:")
    for pool_addr in protocol_pools_list:
        if pool_addr in PROTOCOL_POOL_MINIMUMS:
            min_pct = PROTOCOL_POOL_MINIMUMS[pool_addr]
            min_votes = (P_our * min_pct / Decimal(100)).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
            protocol_pool_minimum_votes[pool_addr] = min_votes
            total_minimum_votes += min_votes
            
            symbol = protocol_pool_symbols.get(pool_addr, pool_addr[:10])
            logger.info(f"  - {symbol}: minimum {min_votes} votes ({float(min_pct)}% of total voting power)")
        else:
            logger.warning(f"  - {pool_addr}: No minimum defined in PROTOCOL_POOL_MINIMUMS")
    
    logger.info(f"Total minimum votes for protocol pools: {total_minimum_votes} ({float(total_minimum_votes/P_our*100):.2f}% of {P_our})")
    
    # Calculate remaining votes after minimum allocations
    votes_for_optimization = P_our - total_minimum_votes
    logger.info(f"Remaining votes for optimization: {votes_for_optimization} ({float(votes_for_optimization/P_our*100):.2f}% of total)")
    
    # Optimize votes for protocol pools first
    # Optimize votes for protocol pools first
    protocol_alloc = []
    if protocol_pool_data:
        # First, allocate minimum votes to each protocol pool
        logger.info(f"Allocating minimum votes to protocol pools, then optimizing remaining votes")
        
        # Start with minimum allocations
        for pool_addr in protocol_pools_list:
            if pool_addr in protocol_pool_minimum_votes:
                min_votes = protocol_pool_minimum_votes[pool_addr]
                protocol_alloc.append((pool_addr, min_votes))
                PROTOCOL_POOL_ALLOCATIONS.append((pool_addr, min_votes))
        
        # If there are remaining votes to optimize, run optimization across all pools (protocol + regular)
        if votes_for_optimization > 0:
            logger.info(f"Optimizing remaining {votes_for_optimization} votes across all pools (protocol + regular)")
            
            # Combine all pools for optimization
            all_pool_data = protocol_pool_data + regular_pool_data
            optimized_alloc = equal_marginal_combined(all_pool_data, votes_for_optimization, S_total, None, gamma, pools)
            
            # Add optimized votes to protocol pools' minimum allocations
            for addr, opt_votes in optimized_alloc:
                if addr in protocol_pools_list:
                    # Find the existing allocation and add to it
                    for i, (alloc_addr, alloc_votes) in enumerate(protocol_alloc):
                        if alloc_addr == addr:
                            protocol_alloc[i] = (addr, alloc_votes + opt_votes)
                            # Update the global tracking
                            for j, (global_addr, global_votes) in enumerate(PROTOCOL_POOL_ALLOCATIONS):
                                if global_addr == addr:
                                    PROTOCOL_POOL_ALLOCATIONS[j] = (addr, alloc_votes + opt_votes)
                            break
                else:
                    # This is a regular pool, will be handled separately
                    pass
            
            # Extract regular pool allocations from the optimization
            regular_alloc = [(addr, votes) for addr, votes in optimized_alloc if addr not in protocol_pools_list]
        else:
            logger.warning("No remaining votes for optimization after minimum protocol allocations!")
            regular_alloc = []
        
        # Log final protocol pool allocations
        total_protocol_votes = sum(votes for _, votes in protocol_alloc)
        logger.info(f"Protocol pools final allocation: {total_protocol_votes} votes ({float(total_protocol_votes/P_our*100):.2f}% of total)")
        
        for addr, votes in protocol_alloc:
            symbol = protocol_pool_symbols.get(addr.lower(), addr[:10])
            min_votes = protocol_pool_minimum_votes.get(addr, Decimal(0))
            opt_votes = votes - min_votes
            logger.info(f"  - {symbol}: {votes} votes (minimum: {min_votes}, optimized: {opt_votes})")
    else:
        logger.info("No protocol pools to optimize")
        # Optimize all votes across regular pools
        logger.info(f"Allocating all {P_our} votes to regular pools")
        regular_alloc = equal_marginal_combined(regular_pool_data, P_our, S_total, None, gamma, pools)
    
    # Combine allocations
    alloc = protocol_alloc + regular_alloc
    total_alloc = sum(d for _, d in alloc)
    
    # Prepare outputs with both vote rewards and LP rewards
    human = []
    bot_lines = []
    
    # Track which protocol pools we've processed
    processed_protocol_pools = set()
    
    for addr, d in alloc:
        if d <= 0:
            continue
        # Skip blacklisted pools - they should never appear in the output
        if addr.lower() in BLACKLISTED_POOLS:
            logger.info(f"Skipping blacklisted pool {addr} from output")
            continue
        p = next((x for x in pools if x["pool"].lower() == addr), None)
        if not p:
            continue
            
        # Mark this protocol pool as processed if applicable
        if any(protocol_addr == addr for protocol_addr, _ in PROTOCOL_POOL_ALLOCATIONS):
            processed_protocol_pools.add(addr)
            
        sym = p.get("symbol", "")
        pct = (d / total_alloc * Decimal(100)).quantize(Decimal('1'), rounding=ROUND_HALF_UP)
        total_usd_dec = Decimal(str(p.get("total_usd", 0)))
        current_pool_weight = Decimal(str(p.get("adjusted_weight", p.get("on_chain_weight", p.get("weight", 0)))))  # Current pool weight (already adjusted)
        new_total_pool_weight = current_pool_weight + d  # Add our new votes to get new total
        fraction = d / new_total_pool_weight if new_total_pool_weight > 0 else Decimal(0)  # Our share of the pool
        
        # Calculate voter-side reward (with volatility adjustment if applicable)
        volatility_penalty = Decimal(1)
        volatility = Decimal(0)
        
        # Apply volatility penalty to voter rewards if enabled
        if gamma > 0 and addr in volatility_map:
            volatility = volatility_map[addr]
            volatility_penalty = max(Decimal(0), Decimal(1) - (volatility / Decimal(100) * gamma))
            logger.debug(f"Pool {sym}: Volatility {volatility:.2f}%, penalty {volatility_penalty:.4f}")
        
        # Apply penalty to voter rewards
        vote_reward_usd = (total_usd_dec * fraction * volatility_penalty).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
        
        # Calculate LP-side reward
        lp_reward_usd = Decimal(0)
        has_lp_data = False
        lp_fraction = Decimal(0)
        
        # Get LP data if available for this pool
        if addr in lp_data:
            has_lp_data = True
            lp_fraction = lp_data[addr]["lp_fraction"]
            is_protocol_pool = next((p.get("is_protocol_pool", False) for p in pools if p["pool"].lower() == addr), False)
            
            # Use reward rate data if available, otherwise fall back to emissions-based calculation
            reward_rate_raw = lp_data[addr].get("reward_rate_raw")
            reward_usd_per_day = lp_data[addr].get("reward_usd_per_day")
            
            if reward_rate_raw is not None and reward_usd_per_day is not None and reward_usd_per_day > 0:
                # Use the exact reward rate from the gauge
                # First, calculate weekly reward in USD
                weekly_reward_usd = reward_usd_per_day * 7
                
                # Our LP position's share of those rewards
                lp_reward_usd = (lp_fraction * weekly_reward_usd).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
                
                # Add debugging information
                if is_protocol_pool:
                    logger.info(f"Protocol pool LP Reward for {sym} using reward rate: effective_fraction={lp_fraction:.6f}, weekly_rewards=${weekly_reward_usd:.2f}, our_rewards=${lp_reward_usd:.2f}")
                else:
                    logger.info(f"LP Reward for {sym} using reward rate: fraction={lp_fraction:.6f}, weekly_rewards=${weekly_reward_usd:.2f}, our_rewards=${lp_reward_usd:.2f}")
            
            # No reward rate available, so no LP rewards
            elif lp_fraction > 0:
                logger.info(f"No reward rate data available for {sym}, LP rewards set to 0")
        
        # Total expected reward from both sources
        total_exp_usd = vote_reward_usd + lp_reward_usd
        
        # Get volatility info if available (we already have volatility from above, just include it in output)
        # Include volatility penalty in the output if applicable
        volatility_penalty_output = float(volatility_penalty) if gamma > 0 and volatility > 0 else None
        
        # Check if this is a protocol pool
        is_protocol_pool = next((p.get("is_protocol_pool", False) for p in pools if p["pool"].lower() == addr), False)
        
        # Get on-chain weight from the original pool data
        on_chain_weight = float(p.get("on_chain_weight", 0))
        
        # Prepare the output entry
        output_entry = {
            "symbol": sym,
            "pool": addr,
            "votes": float(d),
            "votes_human": format_with_suffix(float(d)),
            "on_chain_weight": on_chain_weight,
            "on_chain_weight_human": format_with_suffix(on_chain_weight),
            "pct": int(pct),
            "voter_reward_usd": float(vote_reward_usd),
            "lp_reward_usd": float(lp_reward_usd),
            "total_reward_usd": float(vote_reward_usd + lp_reward_usd),
            "has_lp_position": has_lp_data and lp_fraction > 0,
            "is_protocol_pool": is_protocol_pool,
            "lp_fraction": float(lp_fraction) if has_lp_data else 0.0,
            "volatility": float(volatility) if volatility > 0 else None,
            "volatility_penalty": volatility_penalty_output
        }
        
        # Add protocol pool specific information if applicable
        if is_protocol_pool:
            # Calculate raw ownership vs effective ownership (with 20% boost)
            raw_lp_ownership = float(lp_fraction) if has_lp_data else 0.0
            # Get pool TVL to calculate other LP portion
            p = next((x for x in pools if x["pool"].lower() == addr), None)
            if p and has_lp_data:
                tvl_usd = Decimal(str(p.get("tvl_usd", 0)))
                if tvl_usd > 0:
                    our_lp_value = raw_lp_ownership * tvl_usd
                    other_lp_value = tvl_usd - our_lp_value
                    other_lp_portion = (other_lp_value / tvl_usd) if tvl_usd > 0 else Decimal(0)
                    other_lp_value_weight = Decimal("0.2")  # 20% valuation for other LPs
                    effective_fraction = raw_lp_ownership + (other_lp_portion * other_lp_value_weight)
                    
                    output_entry["protocol_pool_info"] = {
                        "raw_ownership": raw_lp_ownership,
                        "effective_fraction": float(effective_fraction),
                        "other_lp_portion": float(other_lp_portion),
                        "other_lp_value_weight": float(other_lp_value_weight)
                    }
            
        human.append(output_entry)
        
        # Scale to 100e18 total for bot output
        weight_i = (d / P_our * TOTAL_WEIGHT_TARGET).quantize(Decimal('1'), rounding=ROUND_HALF_UP)
        bot_lines.append(f"{addr} {int(weight_i)}")
    
    # Compute total expected USD return (voter + LP rewards)
    total_voter_reward = sum(item['voter_reward_usd'] for item in human)
    total_lp_reward = sum(item['lp_reward_usd'] for item in human)
    total_exp_usd = total_voter_reward + total_lp_reward
    
    # Log breakdown of rewards
    logger.info(f"Total expected voter rewards: ${total_voter_reward:.2f}")
    logger.info(f"Total expected LP rewards: ${total_lp_reward:.2f}")
    logger.info(f"Combined total expected rewards: ${total_exp_usd:.2f}")
    
    # Log if any pools were skipped due to blacklisting
    if BLACKLISTED_POOLS:
        logger.info(f"Note: {len(BLACKLISTED_POOLS)} pools were excluded due to blacklisting")
    
    # Sort by allocation percentage (pct) descending
    human.sort(key=lambda x: x.get('pct', 0), reverse=True)
    
    # Final check to make sure no blacklisted pools are in the output
    # This should not be necessary if the above filtering works correctly, but adding as a safeguard
    human = [item for item in human if item['pool'].lower() not in BLACKLISTED_POOLS]
    
    # Double-check that all protocol pools with allocations are in the output
    logger.info(f"Double-checking protocol pool allocations in output...")
    for protocol_addr, protocol_votes in PROTOCOL_POOL_ALLOCATIONS:
        # Check if this pool is in the processed pools (using case-insensitive matching)
        if not any(item["pool"].lower() == protocol_addr.lower() for item in human) and protocol_votes > 0:
            logger.warning(f"Protocol pool {protocol_addr} was allocated {protocol_votes} votes but is missing from output - adding it")
            
            # Find the pool data
            p = next((x for x in pools if x["pool"].lower() == protocol_addr.lower()), None)
            if p:
                # Calculate the same fields as in the main loop
                sym = p.get("symbol", "")
                pct = (protocol_votes / P_our * Decimal(100)).quantize(Decimal('1'), rounding=ROUND_HALF_UP)
                
                # Get other required fields
                is_protocol_pool = True
                on_chain_weight = float(p.get("on_chain_weight", 0))
                
                # Look up LP data
                lp_fraction = Decimal(0)
                weekly_rewards_usd = Decimal(0)
                addr_lower = protocol_addr.lower()
                
                if addr_lower in lp_data:
                    lp_fraction = lp_data[addr_lower]["lp_fraction"]
                    weekly_rewards_usd = lp_data[addr_lower]["weekly_rewards_usd"]
                
                # Calculate rewards based on the allocation
                current_weight = Decimal(str(p.get("adjusted_weight", p.get("on_chain_weight", p.get("weight", 0)))))
                new_total_weight = current_weight + protocol_votes
                fraction = protocol_votes / new_total_weight if new_total_weight > 0 else Decimal(0)
                total_usd_dec = Decimal(str(p.get("total_usd", 0)))
                vote_reward_usd = (total_usd_dec * fraction).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
                
                # Calculate LP rewards
                lp_reward_usd = Decimal(0)
                if lp_fraction > 0 and weekly_rewards_usd > 0:
                    lp_reward_usd = (lp_fraction * weekly_rewards_usd).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
                    logger.info(f"Added LP reward for missing protocol pool {sym}: lp_fraction={lp_fraction:.6f}, weekly_rewards=${weekly_rewards_usd:.2f}, our_rewards=${lp_reward_usd:.2f}")
                
                # Create the output entry
                output_entry = {
                    "symbol": sym,
                    "pool": protocol_addr,
                    "votes": float(protocol_votes),
                    "votes_human": format_with_suffix(float(protocol_votes)),
                    "on_chain_weight": on_chain_weight,
                    "on_chain_weight_human": format_with_suffix(on_chain_weight),
                    "pct": int(pct),
                    "voter_reward_usd": float(vote_reward_usd),
                    "lp_reward_usd": float(lp_reward_usd),
                    "total_reward_usd": float(vote_reward_usd + lp_reward_usd),
                    "has_lp_position": lp_fraction > 0,
                    "is_protocol_pool": is_protocol_pool,
                    "lp_fraction": float(lp_fraction),
                    "volatility": None,
                    "volatility_penalty": None
                }
                
                # Add protocol pool specific information if applicable
                raw_lp_ownership = float(lp_fraction)
                if p and lp_fraction > 0:
                    tvl_usd = Decimal(str(p.get("tvl_usd", 0)))
                    if tvl_usd > 0:
                        our_lp_value = raw_lp_ownership * tvl_usd
                        other_lp_value = tvl_usd - our_lp_value
                        other_lp_portion = (other_lp_value / tvl_usd) if tvl_usd > 0 else Decimal(0)
                        other_lp_value_weight = Decimal("0.2")  # 20% valuation for other LPs
                        effective_fraction = raw_lp_ownership + (other_lp_portion * other_lp_value_weight)
                        
                        output_entry["protocol_pool_info"] = {
                            "raw_ownership": raw_lp_ownership,
                            "effective_fraction": float(effective_fraction),
                            "other_lp_portion": float(other_lp_portion),
                            "other_lp_value_weight": float(other_lp_value_weight)
                        }
                
                # Add to the human output
                human.append(output_entry)
                
                # Add to bot lines
                weight_i = (protocol_votes / P_our * TOTAL_WEIGHT_TARGET).quantize(Decimal('1'), rounding=ROUND_HALF_UP)
                bot_lines.append(f"{protocol_addr} {int(weight_i)}")
                
                # Resort the list
                human.sort(key=lambda x: x.get('pct', 0), reverse=True)
                
                # Update total rewards
                if vote_reward_usd > 0 or lp_reward_usd > 0:
                    total_voter_reward += float(vote_reward_usd)
                    total_lp_reward += float(lp_reward_usd)
                    total_exp_usd = total_voter_reward + total_lp_reward
                    
                    # Update the human_output totals
                    human_output["total_voter_reward_usd"] = round(total_voter_reward, 2)
                    human_output["total_lp_reward_usd"] = round(total_lp_reward, 2)
                    human_output["total_expected_usd"] = round(total_exp_usd, 2)
    
    # Assemble output with detailed totals
    human_output = {
        "total_voting_power": float(P_our),
        "total_voting_power_human": format_with_suffix(float(P_our)),
        "total_voter_reward_usd": round(total_voter_reward, 2),
        "total_lp_reward_usd": round(total_lp_reward, 2),
        "total_expected_usd": round(total_exp_usd, 2),
        "allocations": human
    }

    
    
    # Add Ouranous Foundation optimization data if available
    if ouranous_relay and ouranous_allocations:
        # Convert allocations to a format similar to our result structure
        ouranous_alloc_list = []
        for addr, votes in ouranous_allocations.items():
            # Skip blacklisted pools in Ouranous Foundation allocations too
            if addr.lower() in BLACKLISTED_POOLS:
                logger.info(f"Skipping blacklisted pool {addr} from Ouranous Foundation output")
                continue
            pool = next((p for p in pools if p["pool"].lower() == addr), None)
            if pool:
                # Get on-chain weight from the original pool data
                on_chain_weight = float(pool.get("on_chain_weight", 0))
                
                ouranous_alloc_list.append({
                    "symbol": pool.get("symbol", ""),
                    "pool": addr,
                    "votes": float(votes),
                    "votes_human": format_with_suffix(float(votes)),
                    "on_chain_weight": on_chain_weight,
                    "on_chain_weight_human": format_with_suffix(on_chain_weight),
                    "pct": float((votes / Decimal(str(ouranous_relay["voting_amount_raw"])) * 100).quantize(Decimal('1'), rounding=ROUND_HALF_UP))
                })
        
        # Sort by votes (descending)
        ouranous_alloc_list.sort(key=lambda x: x["votes"], reverse=True)
        
        # Add to result
        # Add Ouranous Foundation voting power with human-readable format
        ouranous_voting_power = float(ouranous_relay["voting_amount_raw"])
        
        human_output["ouranous_foundation"] = {
            "voting_power": ouranous_voting_power,
            "voting_power_human": format_with_suffix(ouranous_voting_power),
            "allocations": ouranous_alloc_list
        }

        
    
    bot_output = "\n".join(bot_lines)
    
    return human_output, bot_output

def run_optimize(save=True, votes_path=None, with_volatility=False, gamma=1):
    """
    Main entry point for optimizing votes
    
    Args:
        save: Whether to save results to file (True) or display them (False)
        votes_path: Path to the votes dashboard JSON file. If None, uses default path.
        with_volatility: Whether to apply volatility penalty (default False)
        gamma: Volatility penalty coefficient if with_volatility is True (default 1)
    """
    logger.info("Starting vote optimization")
    
    # Load votes dashboard
    dashboard_path = votes_path if votes_path else DEFAULT_DASHBOARD_PATH
    dashboard = load_json(dashboard_path)
    if not dashboard:
        return None
    
    # LP data is now integrated directly in the votes dashboard
    logger.info(f"Using integrated LP data from votes dashboard")
    # Check if LP data is present in the dashboard
    lp_positions = dashboard.get("lp_positions", [])
    if lp_positions:
        logger.info(f"✅ Found {len(lp_positions)} LP positions in votes dashboard")
    else:
        logger.info("⚠️ No LP positions found in votes dashboard, optimizing based on voter rewards only")
    
    # Load volatility data if needed
    volatility_data = None
    if with_volatility:
        volatility_path = "volatility_data/aero/volatility_data.json"
        if os.path.exists(volatility_path):
            logger.info(f"Loading volatility data from {volatility_path}")
            volatility_data = load_json(volatility_path)
            if volatility_data:
                logger.info(f"✅ Loaded volatility data with {len(volatility_data.get('pools', {}))} pools")
            else:
                logger.warning("❌ Failed to load volatility data")
                with_volatility = False  # Disable if load failed
        else:
            logger.warning("⚠️ No volatility data found, disabling volatility adjustment")
            with_volatility = False
    
    # Run optimization with parameters based on flags
    gamma_value = gamma if with_volatility else 0
    
    # Log the individual protocol pool minimums
    logger.info(f"Individual protocol pool minimums:")
    for addr, min_pct in PROTOCOL_POOL_MINIMUMS.items():
        logger.info(f"  - {addr[:10]}...: {min_pct}% of total voting power")
    logger.info(f"Total minimum protocol allocation: {MINIMUM_PROTOCOL_PERCENT}%")
    
    result, bot_output = run_optimization(dashboard, volatility_data, gamma_value, MINIMUM_PROTOCOL_PERCENT)
    
    # If displaying results, show volatility impact on rewards if enabled
    if not save and with_volatility:
        # Run the optimization again without volatility for comparison
        logger.info("\nRunning comparison without volatility to show impact...")
        result_no_vol, _ = run_optimization(dashboard, volatility_data, 0, MINIMUM_PROTOCOL_PERCENT)
        
        # Calculate the difference in expected rewards
        total_with_vol = result['total_expected_usd']
        total_without_vol = result_no_vol['total_expected_usd']
        diff = total_with_vol - total_without_vol
        
        print("\n=== Volatility Impact Analysis ===")
        print(f"Expected return with volatility: ${total_with_vol:.2f}")
        print(f"Expected return without volatility: ${total_without_vol:.2f}")
        print(f"Difference: ${diff:.2f} ({(diff/total_without_vol*100):.2f}%)")
        
        # Compare vote allocation differences for high-volatility pools
        print("\nImpact on high volatility pools (>5%):")
        print("------------------------------------------")
        print("Pool         Vol%  With Vol  Without Vol   Diff    %Change")
        print("------------------------------------------")
        
        # Create maps for easier lookup
        with_vol_map = {a["pool"]: a for a in result["allocations"]}
        without_vol_map = {a["pool"]: a for a in result_no_vol["allocations"]}
        
        # Find pools with significant volatility
        high_vol_pools = [(addr, a) for addr, a in with_vol_map.items() if a.get("volatility", 0) and a.get("volatility", 0) > 5]
        high_vol_pools.sort(key=lambda x: x[1].get("volatility", 0), reverse=True)
        
        # Show differences for top high volatility pools
        for addr, alloc in high_vol_pools[:10]:
            symbol = alloc.get("symbol", "").ljust(10)
            vol = alloc.get("volatility", 0)
            votes_with = alloc.get("votes", 0)
            votes_without = without_vol_map.get(addr, {}).get("votes", 0) if addr in without_vol_map else 0
            diff = votes_with - votes_without
            pct_change = (diff / votes_without * 100) if votes_without > 0 else 0
            print(f"{symbol} {vol:5.1f}%  {votes_with:8.0f}  {votes_without:10.0f}  {diff:+6.0f}  {pct_change:+6.1f}%")
            
        print("\nImpact on pools with largest vote changes:")
        print("------------------------------------------")
        print("Pool         Vol%  With Vol  Without Vol   Diff    %Change")
        print("------------------------------------------")
        
        # Find pools with the largest absolute vote changes
        vote_changes = []
        for addr, alloc in with_vol_map.items():
            if addr in without_vol_map:
                votes_with = alloc.get("votes", 0)
                votes_without = without_vol_map[addr].get("votes", 0)
                diff = votes_with - votes_without
                vol = alloc.get("volatility", 0) or 0
                
                # Only include pools with actual vote changes
                if abs(diff) > 0:
                    vote_changes.append((addr, alloc, diff, vol))
        
        # Sort by absolute difference in votes (largest changes first)
        vote_changes.sort(key=lambda x: abs(x[2]), reverse=True)
        
        for addr, alloc, diff, vol in vote_changes[:10]:
            symbol = alloc.get("symbol", "").ljust(10)
            votes_with = alloc.get("votes", 0)
            votes_without = without_vol_map[addr].get("votes", 0)
            pct_change = (diff / votes_without * 100) if votes_without > 0 else 0
            print(f"{symbol} {vol:5.1f}%  {votes_with:8.0f}  {votes_without:10.0f}  {diff:+6.0f}  {pct_change:+6.1f}%")
    
    
    # Save or display results
    if save:
        save_json(result, HUMAN_OUT_PATH)
        save_text(bot_output, BOT_OUT_PATH)
        logger.info(f"✅ Total expected combined return: ${result['total_expected_usd']:.2f}")
        logger.info(f"   - Voter rewards: ${result['total_voter_reward_usd']:.2f}")
        logger.info(f"   - LP rewards: ${result['total_lp_reward_usd']:.2f}")
        logger.info(f"✅ Allocated votes across {len(result['allocations'])} pools")
    else:
        print("\n================ OPTIMIZATION RESULTS ================")
        print(f"Total Expected USD: ${result['total_expected_usd']:.2f}")
        print(f" - Voter Rewards: ${result['total_voter_reward_usd']:.2f}")
        print(f" - LP Rewards: ${result['total_lp_reward_usd']:.2f}")
        
        # Change header based on whether volatility is enabled
        if with_volatility:
            print("----------------------------------------------------------------")
            print("Pool           Votes     Voter     LP    Total  Vol%   LP Pos")
            print("----------------------------------------------------------------")
        else:
            print("------------------------------------------------------")
            print("Pool           Votes     Voter     LP    Total  LP Pos")
            print("------------------------------------------------------")
        for alloc in result["allocations"][:TOP_N]:
            symbol = alloc.get("symbol", "").ljust(10)
            votes = f"{alloc.get('votes', 0):.0f}".rjust(6)
            voter_reward = f"${alloc.get('voter_reward_usd', 0):.2f}".rjust(8)
            lp_reward = f"${alloc.get('lp_reward_usd', 0):.2f}".rjust(6)
            total_reward = f"${alloc.get('total_reward_usd', 0):.2f}".rjust(8)
            lp_mark = "✓" if alloc.get("has_lp_position", False) else " "
            
            if with_volatility:
                volatility = alloc.get("volatility", None)
                vol_str = f"{volatility:.2f}".rjust(5) if volatility is not None else "  - ".rjust(5)
                print(f"{symbol} {votes} {voter_reward} {lp_reward} {total_reward} {vol_str}  {lp_mark}")
            else:
                print(f"{symbol} {votes} {voter_reward} {lp_reward} {total_reward}  {lp_mark}")
        if len(result["allocations"]) > TOP_N:
            print(f"... and {len(result['allocations']) - TOP_N} more pools")
        print("======================================================\n")
    
    return result
